name: Check Links (reusable)

on:
  workflow_call:

jobs:
  link-checker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: d-morrison/gha/check-links@v1
